name: Bug report
description: Report a reproducible bug in the plugin.
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail for us to reproduce quickly.
  - type: input
    id: redmine_version
    attributes:
      label: Redmine version
      placeholder: "e.g. 5.1.10, 6.1.0, 7.0.0-dev"
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      placeholder: "e.g. 1.0.0-RC"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Endpoint management
        - Delivery processing
        - Payload generation
        - Admin UI
        - Installer/Uninstaller
        - Docs
        - Other
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / stack trace
      render: shell
